version: "3.8"

services:
  app:
    build: .
    container_name: transflow_app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      MONGODB_URL: "mongodb://mongo:27017"
      REDIS_URL: "redis://redis:6379"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
    networks:
      - transflow_net

  consumer:
    build: .
    container_name: transflow_consumer
    command: python -c "import asyncio; from src.consumer import app; asyncio.run(app.run())"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      MONGODB_URL: "mongodb://mongo:27017"
      REDIS_URL: "redis://redis:6379"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
    networks:
      - transflow_net

  mongo:
    image: mongo:6.0
    container_name: transflow_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - transflow_net

  redis:
    image: redis:alpine
    container_name: transflow_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - transflow_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: transflow_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - transflow_net

volumes:
  mongo_data:

networks:
  transflow_net: